// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIuQX2t-NBtyK1YxOzWhrLLfM8l6wQ05Q',
    appId: '1:364538155875:web:18b34c224927d665a13956',
    messagingSenderId: '364538155875',
    projectId: 'movieapp-iti-e79e9',
    authDomain: 'movieapp-iti-e79e9.firebaseapp.com',
    storageBucket: 'movieapp-iti-e79e9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8SkUd9bPKWmpKv6s2VZecyRGzjXRoikg',
    appId: '1:364538155875:android:e5987d3acbe8b408a13956',
    messagingSenderId: '364538155875',
    projectId: 'movieapp-iti-e79e9',
    storageBucket: 'movieapp-iti-e79e9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXByMld6XNpvfRGIEB1qjovMA5VAU5yAU',
    appId: '1:364538155875:ios:5413bdab61dcf02ca13956',
    messagingSenderId: '364538155875',
    projectId: 'movieapp-iti-e79e9',
    storageBucket: 'movieapp-iti-e79e9.firebasestorage.app',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXByMld6XNpvfRGIEB1qjovMA5VAU5yAU',
    appId: '1:364538155875:ios:5413bdab61dcf02ca13956',
    messagingSenderId: '364538155875',
    projectId: 'movieapp-iti-e79e9',
    storageBucket: 'movieapp-iti-e79e9.firebasestorage.app',
    iosBundleId: 'com.example.movieapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIuQX2t-NBtyK1YxOzWhrLLfM8l6wQ05Q',
    appId: '1:364538155875:web:5d26ef8c38899a50a13956',
    messagingSenderId: '364538155875',
    projectId: 'movieapp-iti-e79e9',
    authDomain: 'movieapp-iti-e79e9.firebaseapp.com',
    storageBucket: 'movieapp-iti-e79e9.firebasestorage.app',
  );
}
